spring:
 cloud:
    gateway:
     default-filters:
       - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
     globalcors:
        corsConfigurations:
           '[/**]':
            allowedOrigins: "http://localhost:4000"
            allowedHeaders: "*"
            allowedMethods:
             - GET
             - POST
             - DELETE
             - PUT
             - OPTIONS