INSERT INTO esportes (tem_equipe, nome) VALUES
(false, 'Atletismo'),
(false, 'Badminton'),
(true, 'Basquete'),
(true, 'Basquete 3 x 3'),
(false, 'Boxe'),
(false, 'Breaking'),
(false, 'Canoagem Slalom'),
(false, 'Canoagem Velocidade'),
(false, 'Ciclismo BMX Freestyle'),
(false, 'Ciclismo BMX Racing'),
(false, 'Ciclismo de Estrada'),
(false, 'Ciclismo Moutain Bike'),
(false, 'Escalada Esportiva'),
(false, 'Esgrima'),
(true, 'Futebol'),
(false, 'Ginástica Artística'),
(false, 'Ginástica de Trampolim'),
(false, 'Ginástica Rítmica'),
(false, 'Golfe'),
(true, 'Handebol'),
(false, 'Hipismo'),
(true, 'Hóquei sobre Grama'),
(false, 'Judô'),
(false, 'Levantamento de Peso'),
(false, 'Luta'),
(false, 'Maratona Aquática'),
(false, 'Nado Artístico'),
(false, 'Natação'),
(false, 'Pentatlo Moderno'),
(true, 'Polo Aquático'),
(false, 'Remo'),
(true, 'Rugby Sevens'),
(false, 'Saltos Ornamentais'),
(false, 'Skate'),
(false, 'Surfe'),
(false, 'Taekwondo'),
(false, 'Tênis'),
(false, 'Tênis de Mesa'),
(false, 'Tiro com Arco'),
(false, 'Triatlo'),
(false, 'Vela'),
(true, 'Vôlei'),
(true, 'Vôlei de Praia');